// Code generated by MockGen. DO NOT EDIT.
// Source: go-connector/services/client (interfaces: StratumnClient)

// Package mockclient is a generated GoMock package.
package mockclient

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStratumnClient is a mock of StratumnClient interface
type MockStratumnClient struct {
	ctrl     *gomock.Controller
	recorder *MockStratumnClientMockRecorder
}

// MockStratumnClientMockRecorder is the mock recorder for MockStratumnClient
type MockStratumnClientMockRecorder struct {
	mock *MockStratumnClient
}

// NewMockStratumnClient creates a new mock instance
func NewMockStratumnClient(ctrl *gomock.Controller) *MockStratumnClient {
	mock := &MockStratumnClient{ctrl: ctrl}
	mock.recorder = &MockStratumnClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStratumnClient) EXPECT() *MockStratumnClientMockRecorder {
	return m.recorder
}

// CallAccountGql mocks base method
func (m *MockStratumnClient) CallAccountGql(arg0 context.Context, arg1 string, arg2 map[string]interface{}, arg3 interface{}) error {
	ret := m.ctrl.Call(m, "CallAccountGql", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CallAccountGql indicates an expected call of CallAccountGql
func (mr *MockStratumnClientMockRecorder) CallAccountGql(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallAccountGql", reflect.TypeOf((*MockStratumnClient)(nil).CallAccountGql), arg0, arg1, arg2, arg3)
}

// CallTraceGql mocks base method
func (m *MockStratumnClient) CallTraceGql(arg0 context.Context, arg1 string, arg2 map[string]interface{}, arg3 interface{}) error {
	ret := m.ctrl.Call(m, "CallTraceGql", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CallTraceGql indicates an expected call of CallTraceGql
func (mr *MockStratumnClientMockRecorder) CallTraceGql(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallTraceGql", reflect.TypeOf((*MockStratumnClient)(nil).CallTraceGql), arg0, arg1, arg2, arg3)
}
