// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stratumn/go-connector/services/livesync (interfaces: Synchronizer)

// Package mocksynchronizer is a generated GoMock package.
package mocksynchronizer

import (
	gomock "github.com/golang/mock/gomock"
	go_chainscript "github.com/stratumn/go-chainscript"
	livesync "github.com/stratumn/go-connector/services/livesync"
	reflect "reflect"
)

// MockSynchronizer is a mock of Synchronizer interface
type MockSynchronizer struct {
	ctrl     *gomock.Controller
	recorder *MockSynchronizerMockRecorder
}

// MockSynchronizerMockRecorder is the mock recorder for MockSynchronizer
type MockSynchronizerMockRecorder struct {
	mock *MockSynchronizer
}

// NewMockSynchronizer creates a new mock instance
func NewMockSynchronizer(ctrl *gomock.Controller) *MockSynchronizer {
	mock := &MockSynchronizer{ctrl: ctrl}
	mock.recorder = &MockSynchronizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSynchronizer) EXPECT() *MockSynchronizerMockRecorder {
	return m.recorder
}

// Register mocks base method
func (m *MockSynchronizer) Register(arg0 livesync.WorkflowStates) <-chan []*go_chainscript.Link {
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(<-chan []*go_chainscript.Link)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockSynchronizerMockRecorder) Register(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockSynchronizer)(nil).Register), arg0)
}
